name = "dogoakiheyasysytem-tama3"
main = "worker.py"
compatibility_date = "2024-12-02"
compatibility_flags = ["python_workers"]

[[kv_namespaces]]
binding = "STATE_KV"
id = "0f70862e45bc4f7d997de980cd1f8b21"
